/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RegulamentoRouteImport } from './routes/regulamento'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMeusPalpitesRouteImport } from './routes/_authenticated/meus-palpites'
import { Route as AuthenticatedPalpitarRouteImport } from './routes/_authenticated/palpitar'
import { Route as ApiPublicGetFixturesIndexRouteImport } from './routes/api/public/get-fixtures/index'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulamentoRoute = RegulamentoRouteImport.update({
  id: '/regulamento',
  path: '/regulamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusPalpitesRoute =
  AuthenticatedMeusPalpitesRouteImport.update({
    id: '/meus-palpites',
    path: '/meus-palpites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPalpitarRoute = AuthenticatedPalpitarRouteImport.update({
  id: '/palpitar',
  path: '/palpitar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicGetFixturesIndexRoute =
  ApiPublicGetFixturesIndexRouteImport.update({
    id: '/api/public/get-fixtures/',
    path: '/api/public/get-fixtures/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/pagamento': typeof PagamentoRoute
  '/ranking': typeof RankingRoute
  '/regulamento': typeof RegulamentoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/meus-palpites': typeof AuthenticatedMeusPalpitesRoute
  '/palpitar': typeof AuthenticatedPalpitarRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/get-fixtures/': typeof ApiPublicGetFixturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/pagamento': typeof PagamentoRoute
  '/ranking': typeof RankingRoute
  '/regulamento': typeof RegulamentoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/meus-palpites': typeof AuthenticatedMeusPalpitesRoute
  '/palpitar': typeof AuthenticatedPalpitarRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/get-fixtures': typeof ApiPublicGetFixturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/pagamento': typeof PagamentoRoute
  '/ranking': typeof RankingRoute
  '/regulamento': typeof RegulamentoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/meus-palpites': typeof AuthenticatedMeusPalpitesRoute
  '/_authenticated/palpitar': typeof AuthenticatedPalpitarRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/get-fixtures/': typeof ApiPublicGetFixturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/pagamento'
    | '/ranking'
    | '/regulamento'
    | '/admin'
    | '/meus-palpites'
    | '/palpitar'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/get-fixtures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/pagamento'
    | '/ranking'
    | '/regulamento'
    | '/admin'
    | '/meus-palpites'
    | '/palpitar'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/get-fixtures'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/entrar'
    | '/pagamento'
    | '/ranking'
    | '/regulamento'
    | '/_authenticated/admin'
    | '/_authenticated/meus-palpites'
    | '/_authenticated/palpitar'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/get-fixtures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  PagamentoRoute: typeof PagamentoRoute
  RankingRoute: typeof RankingRoute
  RegulamentoRoute: typeof RegulamentoRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
  ApiPublicGetFixturesIndexRoute: typeof ApiPublicGetFixturesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamento': {
      id: '/regulamento'
      path: '/regulamento'
      fullPath: '/regulamento'
      preLoaderRoute: typeof RegulamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-palpites': {
      id: '/_authenticated/meus-palpites'
      path: '/meus-palpites'
      fullPath: '/meus-palpites'
      preLoaderRoute: typeof AuthenticatedMeusPalpitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/palpitar': {
      id: '/_authenticated/palpitar'
      path: '/palpitar'
      fullPath: '/palpitar'
      preLoaderRoute: typeof AuthenticatedPalpitarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/get-fixtures/': {
      id: '/api/public/get-fixtures/'
      path: '/api/public/get-fixtures'
      fullPath: '/api/public/get-fixtures/'
      preLoaderRoute: typeof ApiPublicGetFixturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMeusPalpitesRoute: typeof AuthenticatedMeusPalpitesRoute
  AuthenticatedPalpitarRoute: typeof AuthenticatedPalpitarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMeusPalpitesRoute: AuthenticatedMeusPalpitesRoute,
  AuthenticatedPalpitarRoute: AuthenticatedPalpitarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EntrarRoute: EntrarRoute,
  PagamentoRoute: PagamentoRoute,
  RankingRoute: RankingRoute,
  RegulamentoRoute: RegulamentoRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
  ApiPublicGetFixturesIndexRoute: ApiPublicGetFixturesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
